services:
  app:
    build:
      context: .
    # environment:
    #  BASE_URL: "https://iiif.tiramis2.doshisha.ac.jp/"
    #  IMAGES_DIR: "/data/images/"
    #  TZ: "Asia/Tokyo"
    command: entrypoint.sh
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - .:/code
      # - /files/tirdb/pyramids/:/data/images/:ro
    # networks:
    #   default:
    #     ipv4_address: 10.200.12.10
  iipsrv:
    image: ghcr.io/dfukagaw28/iipsrv:1.2
    restart: always
    # volumes:
    #   - /files/tirdb/pyramids/:/data/images/:ro

# networks:
#  default:
#    ipam:
#      config:
#        - subnet: 10.200.12.0/24
